### ISSUE TITLE
Excessive template repo downloads

### ISSUE THREAD

**Issue by nickwalkmsft** [microsoft/docs-scaffolding#41]
The extension appears to download and unzip a new copy of `learn-scaffolding-main.zip` without cleaning it up every time I open a new VSCode window. Can it be optimized at all?

**Comment by jamarw** [comment]
Hi @nickwalkmsft , we can get a fix in for this. I'll link the PR and let you know when the fixed has shipped. Thanks!

**Comment by nickwalkmsft** [comment]
Hey cool, thanks!

Wanted to say that I love the extension, keep up the great work.

**Comment by jamarw** [comment]
https://github.com/microsoft/docs-scaffolding/pull/43

**Comment by jamarw** [comment]
Hi @nickwalkmsft, this issue iss resolved in release 0.0.5. Thanks again for the feedback!
