### ISSUE TITLE
Can't run any of the create new module actions

### ISSUE THREAD

**Issue by PhilStollery** [microsoft/docs-scaffolding#59]
Either from a right click or the command palette. If I try and run Learn: Create module in NEW folder the error I get is 'scaffoldModule' failed. 

I've removed and re-added the Docs Authoring Pack - made sure I have the latest version of VS Code - still getting the error. Same for the create module in current folder. Is it relate to the 0.0.8 release?

**Comment by PhilStollery** [comment]
![image](https://user-images.githubusercontent.com/34449786/121340449-88b62000-c917-11eb-94a8-38a3d5c043a7.png)

**Comment by PhilStollery** [comment]
0.0.7 works.

**Comment by nickwalkmsft** [comment]
Same here. When you try to create a new module in a current or new folder, you get this in the extension host log:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
	at validateString (internal/validators.js:124:11)
	at Object.join (path.js:375:7)
	at c:\Users\nickwalk\.vscode\extensions\docsmsft.docs-scaffolding-0.0.8\out\controllers\scaffolding-controller.js:46:46
	at Generator.next (<anonymous>)
	at c:\Users\nickwalk\.vscode\extensions\docsmsft.docs-scaffolding-0.0.8\out\controllers\scaffolding-controller.js:9:71
	at new Promise (<anonymous>)
	at __awaiter (c:\Users\nickwalk\.vscode\extensions\docsmsft.docs-scaffolding-0.0.8\out\controllers\scaffolding-controller.js:5:12)
	at scaffoldModule (c:\Users\nickwalk\.vscode\extensions\docsmsft.docs-scaffolding-0.0.8\out\controllers\scaffolding-controller.js:45:12)
        ...
```

That's [here](https://github.com/microsoft/docs-scaffolding/blob/main/src/controllers/scaffolding-controller.ts#L54-L58). I'm not an extension developer but it appears that the activation process is failing and so `localTemplateRepoPath` isn't populated. Further evidence of this is that `homedir()/Docs Authoring` isn't getting created on startup if it doesn't exist.

There's nothing else interesting in the extension host log, but I do get an error in the developer tools during activation with the following at the top of the stack trace:

```
Cannot find module 'c:\Users\nickwalk\.vscode\extensions\docsmsft.docs-scaffolding-0.0.8\node_modules\cacheable-request\src\index.js'. Please verify that the package.json has a valid "main" entry`
```

`c:\Users\nickwalk\.vscode\extensions\docsmsft.docs-scaffolding-0.0.8\node_modules\cacheable-request\src` is missing entirely. If I go download it and manually jam it in there, I get the same error again but for the `responselike` package, which is also missing its `src` directory. I didn't chase it any further than that, but I do see that those directories aren't in the extension's .vsix.

**Did something go wrong during packaging?**

**Comment by jamarw** [comment]
Hi @PhilStollery @nickwalkmsft , sorry for the late response but I didn't see a notification for this issue. I think it may have been a packaging issue. I'm going to release an update today so we can get this fixed. 

There is an option to install different versions if you need to rollback so you're not blocked. I've added a clip below in case you need the steps. Thanks again for reporting this.

![rollback](https://user-images.githubusercontent.com/11825888/122071873-f517a000-cdab-11eb-8bb3-38ac3cdef38b.gif)

**Comment by jamarw** [comment]
Hi @nickwalkmsft @PhilStollery, I found a couple issues with some of our dependencies which affected the scaffolding process. A new release, v.0.0.9, was just released which should fix these problems. I just ran a test pass and things look to be working as expected. Thanks again for letting us know about this problem and feel free to reach out if you notice anything else.
